version: "3.3"

services:
  tester:
    image: ${DOCKER_IMG}
    container_name: aaqua_tester
    command: pytest /service/src/
    networks:
      - aaqua_net
    depends_on:
      - server
    profiles:
      - test

  server:
    image: ${DOCKER_IMG}
    container_name: aaqua_server
    command: python /service/src/main.py --grpc-port=${GRPC_PORT} --rest-port=${REST_PORT}
    ports:
      - ${REST_PORT}:${REST_PORT}
    networks:
      - aaqua_net

networks:
  aaqua_net:
